//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeutrinoStudio.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeutrinoStudio.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 NEUTRINO Studio 的本地化字符串。
        /// </summary>
        public static string Common_AppName {
            get {
                return ResourceManager.GetString("Common_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About NEUTRINO Studio 的本地化字符串。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Debug 的本地化字符串。
        /// </summary>
        public static string Menu_Debug {
            get {
                return ResourceManager.GetString("Menu_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Edit 的本地化字符串。
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Generate 的本地化字符串。
        /// </summary>
        public static string Menu_Generate {
            get {
                return ResourceManager.GetString("Menu_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Log 的本地化字符串。
        /// </summary>
        public static string Menu_Log {
            get {
                return ResourceManager.GetString("Menu_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Monitor 的本地化字符串。
        /// </summary>
        public static string Menu_Monitor {
            get {
                return ResourceManager.GetString("Menu_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Project 的本地化字符串。
        /// </summary>
        public static string Menu_Project {
            get {
                return ResourceManager.GetString("Menu_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Queue 的本地化字符串。
        /// </summary>
        public static string Menu_Queue {
            get {
                return ResourceManager.GetString("Menu_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Quit 的本地化字符串。
        /// </summary>
        public static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Run 的本地化字符串。
        /// </summary>
        public static string Menu_Run {
            get {
                return ResourceManager.GetString("Menu_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Settings 的本地化字符串。
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Stop 的本地化字符串。
        /// </summary>
        public static string Menu_Stop {
            get {
                return ResourceManager.GetString("Menu_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ta_sk 的本地化字符串。
        /// </summary>
        public static string Menu_Task {
            get {
                return ResourceManager.GetString("Menu_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Task 的本地化字符串。
        /// </summary>
        public static string Menu_TaskView {
            get {
                return ResourceManager.GetString("Menu_TaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Tools 的本地化字符串。
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _View 的本地化字符串。
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Welcome 的本地化字符串。
        /// </summary>
        public static string Menu_Welcome {
            get {
                return ResourceManager.GetString("Menu_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        public static string ProjectView_Title {
            get {
                return ResourceManager.GetString("ProjectView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsView_Titile {
            get {
                return ResourceManager.GetString("SettingsView_Titile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task 的本地化字符串。
        /// </summary>
        public static string TaskView_Title {
            get {
                return ResourceManager.GetString("TaskView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string WelcomeView_Title {
            get {
                return ResourceManager.GetString("WelcomeView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome Back! 的本地化字符串。
        /// </summary>
        public static string WelcomeView_WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeView_WelcomeBack", resourceCulture);
            }
        }
    }
}
